CON-2670:Sql script to get the Completed & Stopped apprenticeship
SkillsFundingAgency/das-forecasting-tool pull request #280
Opened 2020-12-01 08:52 UTC by VasanthaKasirajan3008

2020-12-03 09:14 UTC, hkf-tech requested changes

2020-12-03 09:14 UTC, hkf-tech commented on src/SFA.DAS.Forecasting.Database/AdhocScripts/Manual/CON-2670-stopped-apprenticeship.sql
> +	SET ActualEndDate = TC.CompletionDate , Status = 1
invalid column CompletetionDate

2020-12-03 09:30 UTC, VasanthaKasirajan3008 commented on src/SFA.DAS.Forecasting.Database/AdhocScripts/Manual/CON-2670-stopped-apprenticeship.sql
> +	SET ActualEndDate = TC.CompletionDate , Status = 1
should be Stop date, changed.

2020-12-03 14:50 UTC, hkf-tech submitted a review, later dismissed

2020-12-23 14:07 UTC, hkf-tech approved these changes

2021-01-04 12:09 UTC, merged